name: tsacdop
description: An open source podacasts player.

version: 0.5.0+38

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_animated: ^2.1.0
  audio_session: ^0.0.8
  cached_network_image: ^2.3.2+1
  color_thief_flutter: ^1.0.2
  confetti: ^0.5.4+1
  cookie_jar: ^1.0.1
  cupertino_icons: ^1.0.0
  connectivity: ^0.4.9
  convert: ^2.1.1
  crypto: ^2.1.5
  device_info: ^0.4.2+8
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  extended_nested_scroll_view: ^1.0.1
  effective_dart: ^1.2.4
  equatable: ^1.2.5
  feature_discovery: ^0.10.0
  file_picker: ^2.0.7
  flutter_html: ^0.11.1
  flutter_downloader: ^1.5.1
  fluttertoast: ^4.0.0
  flutter_isolate: ^1.0.0+14
  flutter_linkify: ^3.1.3
  flutter_file_dialog: ^0.0.5
  flare_flutter: ^2.0.6
  fl_chart: ^0.12.0
  marquee: ^1.6.1
  google_fonts: ^1.1.0
  image: ^2.1.18
  intl: ^0.16.1
  json_serializable: ^3.5.0
  json_annotation: ^3.1.0
  path_provider: ^1.6.18
  permission_handler: ^5.0.1
  provider: ^4.3.2
  rxdart: ^0.24.1
  sqflite: ^1.3.1+1
  shared_preferences: ^0.5.12
  tuple: ^1.0.3
  url_launcher: ^5.7.2
  uuid: ^2.2.2
  xml: ^4.2.0
  workmanager: ^0.2.3
  wc_flutter_share: ^0.2.2
  audio_service: ^0.15.1
  just_audio:
    git:
      url: https://github.com/stonega/just_audio.git
  line_icons:
    git:
      url: https://github.com/galonsos/line_icons.git
  focused_menu:
    git:
      url: https://github.com/stonega/focused_menu.git
  webfeed:
    git:
      url: https://github.com/stonega/webfeed.git

dependency_overrides:
  linkify:
    git:
      url: https://github.com/stonega/linkify.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0

flutter:
  assets:
    - assets/
  uses-material-design: true
flutter_intl:
  enabled: true
  localizely:
    project_id: bde4e9bd-4cb2-449b-9de2-18f231ddb47d
