name: tsacdop
description: An open source podcast player.

version: 0.6.0+48

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_animated: ^3.0.0
  audio_session: ^0.1.0
  cached_network_image: ^3.1.0
  color_thief_flutter: ^1.0.2
  confetti: ^0.5.5
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.3
  crypto: ^3.0.1
  device_info: ^2.0.2
  dio_cookie_manager: ^2.0.0
  dio: ^4.0.0
  extended_nested_scroll_view: ^3.0.0
  effective_dart: ^1.3.1
  feature_discovery: ^0.14.0
  file_picker: ^3.0.1
  flutter_html: 0.11.1
  fluttertoast: ^4.0.1
  flutter_isolate: ^2.0.0
  flutter_linkify: ^4.1.0
  flutter_file_dialog: ^2.1.1
  flare_flutter: ^3.0.2
  fl_chart: ^0.36.4
  line_icons: ^2.0.1
  flutter_media_metadata: ^0.1.1
  marquee: ^2.0.0
  google_fonts: ^2.1.0
  image: ^3.0.2
  intl: ^0.17.0
  json_serializable: ^4.1.0
  json_annotation: ^4.0.1
  permission_handler: ^6.1.1
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  state_notifier: ^0.7.0
  tuple: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  workmanager: ^0.2.3
  wc_flutter_share: ^0.4.0
  xml: ^5.2.0
  audio_service: 0.18.0
  just_audio:
    git:
      url: https://github.com/stonega/just_audio_origin.git
      ref: update
      path: just_audio
  flutter_downloader:
    git:
      url: https://github.com/stonega/flutter_downloader.git
  focused_menu:
    git:
      url: https://github.com/stonega/focused_menu.git
  webfeed:
    git:
      url: https://github.com/stonega/webfeed.git
  equatable: ^2.0.0
  path_provider: ^2.0.1
  http_parser: ^4.0.0

dependency_overrides:
  meta: 1.3.0
  shared_preferences: 2.0.0
  linkify:
    git:
      url: https://github.com/stonega/linkify.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.11

flutter:
  assets:
    - assets/
  uses-material-design: true
flutter_intl:
  enabled: true
  localizely:
    project_id: bde4e9bd-4cb2-449b-9de2-18f231ddb47d
